#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Stable Extension Distribution Pipeline
on:
  pull_request:
    branches:
      - v1.1.3
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  push:
    branches:
      - v1.1.3
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.1.3
    with:
      duckdb_version: v1.1.3
      extension_name: spatial
      ci_tools_version: v1.1.3
      vcpkg_commit: 5e5d0e1cd7785623065e77eff011afdeec1a3574
      exclude_archs: 'wasm_threads;wasm_eh;wasm_mvp;windows_amd64_mingw;windows_amd64;osx_arm64;osx_amd64;linux_arm64;linux_amd64_gcc4;linux_amd64'
